services:
  - type: web
    name: rnr-blog
    env: ruby
    plan: free
    region: oregon
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: rnr-blog-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

databases:
  - name: rnr-blog-db
    databaseName: rnr_blog
    user: rnr_blog
    plan: free
    region: oregon
